In [1]:
import gym
import random
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from collections import deque
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import Sequential

In [2]:
def model():
    model = Sequential()
    model.add(Dense(24, input_dim=4, activation='relu'))
    model.add(Dense(24, activation='relu'))
    model.add(Dense(2, activation='linear'))
    model.compile(loss='mse', optimizer=Adam(lr=0.001))
    return model

model = model()



In [6]:
model.predict(np.array([1,2,3,4]).reshape(1,4), verbose=0)

array([[1.1166147, 0.6612125]], dtype=float32)

In [4]:
model(np.array([1,2,3,4]).reshape(1,4))

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1.1166147, 0.6612125]], dtype=float32)>

In [5]:
model(np.array([1,2,3,4]).reshape(1,4)).numpy()

array([[1.1166147, 0.6612125]], dtype=float32)